- manifest-diff.sh
Adds a manifest diffing script that compares master versions of two manifests from github.com/uc-cdis. 
- Might extend in future by enabling diffing 2+ manifests
- Also might extend by diffing against a 'default' manifest with documentation?
- Another idea -- customizable diffing tool
> Add manifest diffing script

- README.md
- generate_release_notes.sh
- make_branch.sh
- repo_list.txt
Script to generate release notes for Gen3 Monthly Releases
Documentation updated
> script to generate release notes

- repo_list.txt
> chore:adding more repositories to the release process

- jenkins-jobs/push-gen3-monthly-release-images-to-aws-ecr.sh
> chore(quay-ecr-sync): Set correct quay repo name for dataguids.org

- jenkins-jobs/deploy-gen3-release-to-environment.sh
> fix: fix syntax error

- gen3release-sdk/gen3release/config/env.py
removing svcs from `svcs_to_ignore` list
> Removing services from ignore list

- jenkins-jobs/create-jiras-for-gen3-monthly-release.sh
- jenkins-jobs/create-release-pr-from-qa-to-prod.sh
- jenkins-jobs/create-release-pr.sh
- jenkins-jobs/deploy-gen3-release-to-environment.sh
- jenkins-jobs/gen3-migrate-user-yamls.sh
- jenkins-jobs/gen3-qa-harvest-metrics-and-plot-graphs.sh
- jenkins-jobs/gen3-qa-monthly-release-notes-generator.sh
- jenkins-jobs/gen3-qa-monthly-release-notes-generator_scheduled.sh
- jenkins-jobs/mark-gen3-monthly-release-as-released.sh
- jenkins-jobs/update-ci-env-with-latest-integration-branch.groovy
To allow new pieces of automation that require newer py versions.
> chore(productivity): Upgrade python to 3.8 on gen3-qa-worker

- jenkins-jobs/gen3-run-load-tests.groovy
Adding new audit service load testing part to the jenkins-job script
> chore: add audit-service load test part

- jenkins-jobs/saturation-alerts.groovy
Monitor both jenkins-master and jenkins-ci-worker
> chore(reliability): Disk space usage Slack alerts for CI infra

- jenkins-jobs/push-gen3-monthly-release-images-to-aws-ecr.sh
> fix(quay-ecr-replication): Pick up correct slack webhook

- jenkins-jobs/nightly-job-run.sh
To improve visibility of changes, peer review and collaborative improvement.
> chore(nightly-build): Keep the nightly source under version control

- jenkins-jobs/close_old_nightly_build_prs.py
quick script to clean old nightly build PRs.
> chore(nightly-build): Introduce script to clean old nightly-build PRs

- jenkins-jobs/nightly-job-run.sh
Hardcoded values are not cool.
> fix(nightly-build): Capture correct portal/sower/guppy blocks

- jenkins-jobs/update-ci-env-with-latest-integration-branch.groovy
changing the creds in the script to use creds from Jenkins1
Jenkins 2 jenkins job would be using the script from THOR repo
> Update creds to use jenkins1 credentials

- jenkins-jobs/update-ci-env-with-latest-integration-branch.groovy
The old code was too awkward with a bunch of unnecessary steps.
> chore(update-ci-env): Refactor code to update ci-env with integration branch

- jenkins-jobs/check_quay_image.py
This script will check if the Quay Images are ready before the sanity check for the Release
> chore : adding quay image check script

- jenkins-jobs/self-service-run-gen3-job.groovy
Jenkins job to run gen3 jobs specifying TARGET_ENVIRONMENT and JOB_NAME
https://jenkins.planx-pla.net/job/self-service-run-gen3-job/
> Generic jenkins job to run gen3 jobs

- jenkins-jobs/create-gen3-release-candidate-branch_scheduled.sh
> fix branch name logic

- jenkins-jobs/create-gen3-release-candidate-branch_scheduled.sh
> remove dot in integration branch name

- jenkins-jobs/gen3-run-all-load-tests-for-release-testing.groovy
this is the only one that is remaining
> add more missing parameters

- repo_list.txt
> Adding requestor to repo_list.txt

- delete_branch.sh
> chore: script to delete branch and quay images

- jenkins-jobs/quay-apply-new-tag-to-img.sh
add all jenkins scripts to source control
> chore(release-mgmt): Add script to apply new docker img tag

- README.md
- jenkins-jobs/create-gen3-release-candidate-branch.sh
- jenkins-jobs/gen3-qa-monthly-release-notes-generator_scheduled.sh
- jenkins-jobs/merge-integration-branch-into-stable-and-tag.sh
- jenkins-jobs/merge-integration-branch-into-stable-and-tag_scheduled.sh
> fix script paths after reorganizing the folders

- jenkins-jobs/delete-ecr-images.sh
Script to delete stale integration branches from AWS ECR after the Release is completed
> chore:script to delete stale integration branch from ECR

- jenkins-jobs/self-service-run-gen3-job.groovy
> run kube-setup-secrets before running jenkins job

- gen3release-sdk/gen3release/config/env.py
Adding `covid19-bayes` svc to ignore-list
> Adding covid19-bayes svc to ignore list

- jenkins-jobs/make_stable_and_tag.sh
- jenkins-jobs/merge-integration-branch-into-stable-and-tag_scheduled.sh
Will be closing this PR after the release is done
> Fix logic for merging stable and tagging

- gen3release-sdk/release_jiras.py
Change the release ticket structure from `Epic -> Story` to `Story -> Sub-task` to prevent creating too many epics in the project. All these stories would be linked to a single epic called `Monthly Release Activities` (https://ctds-planx.atlassian.net/browse/QAT-350)
Result of a test run - https://ctds-planx.atlassian.net/browse/QAT-351
> Restructure release jira tickets

- other_scripts/deploy-release-tickets.py
- Add script to create tickets to deploy releases
> Add script to create tickets to deploy releases

- jenkins-jobs/gen3-run-all-load-tests-for-release-testing.groovy
to avoid this error
`groovy.lang.MissingPropertyException: No such property: MTLS_DOMAIN for class: groovy.lang.Binding`
> add MTLS_DOMAIN to parameter list

- jenkins-jobs/self-service-run-gen3-job.groovy
fail the script if there is any error which causes Jenkins job to fail
> make the job fail if error

- gen3release-sdk/gen3release/config/env.py
> ignore frontend-framework in release PRs

- jenkins-jobs/self-service-run-gen3-job.groovy
> roll services before running the job

- jenkins-jobs/apply-new-monthly-release-tag-to-all-imgs.groovy
- jenkins-jobs/check_quay_image.py
- jenkins-jobs/delete-ecr-images.sh
- jenkins-jobs/push-gen3-monthly-release-images-to-aws-ecr.sh
- repo_list.txt
> remove mariner from release automation

- gen3release-sdk/gen3release/env_cli.py
Reverts uc-cdis/gen3-release-utils#182
> Revert "exit when manifest file not exist"

- jenkins-jobs/nightly-job-run.sh
Jira Ticket: [PXP-9890](https://ctds-planx.atlassian.net/browse/PXP-9890)
- Rotate through nightly build environments
> (PXP-9890): rotate through nightly build environments

- jenkins-jobs/deploy-gen3-release-to-environment.sh
> fix version change for portal from quay

- jenkins-jobs/gen3-run-load-tests-v2.groovy
updated branch name in load test script
> updated branch name

- jenkins-jobs/update-ci-env-with-latest-integration-branch.groovy
> updating PR title when the job is excuted

- jenkins-jobs/apply-new-monthly-release-tag-to-all-imgs.groovy
- jenkins-jobs/check_quay_image.py
- jenkins-jobs/check_quay_image_up_to_date.py
- jenkins-jobs/delete-ecr-images.sh
Jira Ticket: [QAT-543](https://ctds-planx.atlassian.net/browse/QAT-543)
> add batch-export to sower jobs list

- jenkins-jobs/check-release-images-in-ecr.sh
Jira Ticket: [QAT-579](https://ctds-planx.atlassian.net/browse/QAT-570)
> chore : check release image exist in ect

- jenkins-jobs/gen3-run-load-tests.groovy
removing duplicate `studyViewer` block from load test script
> remove duplicate studyViewer load test block

- .github/workflows/unit_tests.yml
- .pre-commit-config.yaml
- jenkins-jobs/close_old_nightly_build_prs.py
Jira Ticket: [PXP-10313](https://ctds-planx.atlassian.net/browse/PXP-10313)
- `close_old_nightly_build_prs` job: also delete old nightly build branches
> PXP-10313 close_old_nightly_build_prs: delete branches too

- gen3release-sdk/gen3release/config/env.py
> add kayako-wrapper to ignore list

- gen3release-sdk/release_jiras.py
[QAT-674](https://ctds-planx.atlassian.net/browse/QAT-674)
remove jingh and add yogeshk
> updating the team_member list

- gen3release-sdk/gen3release/config/env.py
> ignore dicom services

- gen3release-sdk/release_jiras.py
> update the team member list

- jenkins-jobs/gen3-run-load-tests.groovy
> scaling indexd pods for the loadTests

- jenkins-jobs/check-release-images-in-ecr.sh
[GQE-37](https://ctds-planx.atlassian.net/browse/GQE-37)
[GQE-37]: https://ctds-planx.atlassian.net/browse/GQE-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix the check ecr for release script

- gen3release-sdk/gen3release/config/env.py
> Ignore cedar-wrapper in automated release deployment

- jenkins-jobs/gen3-run-load-tests.groovy
> updating the loadTest indexd record file

- jenkins-jobs/gen3-qa-monthly-release-notes-generator_scheduled.sh
> update the python version to 3.9 for gen3-qa-worker jobs

- jenkins-jobs/gen3-run-load-tests.groovy
> Testing jenkins-perf for load testing

- jenkins-jobs/gen3-run-all-load-tests-for-release-testing.groovy
- jenkins-jobs/gen3-run-load-tests.groovy
> update the create indexd record load test creds

- jenkins-jobs/gen3-run-load-tests.groovy
> Add PUPPETEER SKIP in script

- jenkins-jobs/gen3-run-load-tests.groovy
load tests for indexd are failing and we believe it is due to line 216
> removing line 216 as it is a duplicate of line 141

- gen3release-sdk/gen3release/config/env.py
Jira Ticket: [GQE-128](https://ctds-planx.atlassian.net/browse/GQE-128)
These two stay unchanged during releases.
[GQE-128]: https://ctds-planx.atlassian.net/browse/GQE-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update env.py to exclude orthanc and ohif

- jenkins-jobs/gen3-run-load-tests.groovy
> update the indexing admin user

- gen3release-sdk/gen3release/config/env.py
> (Chore): Ignore datareplicate

- release_names.csv
> Add release names

- gen3release-sdk/gen3release/config/env.py
Link to JIRA ticket if there is one: [GQE-167](https://ctds-planx.atlassian.net/browse/GQE-167)
[GQE-167]: https://ctds-planx.atlassian.net/browse/GQE-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Skip portal version update for dataguids repo

- jenkins-jobs/nightly-job-run.sh
Anvil is removed from cdis-manifest
Link to JIRA ticket if there is one:
> Do not use anvil for nightly builds

- gen3release-sdk/gen3release/gith/git.py
- gen3release-sdk/release_jiras.py
Link to JIRA ticket if there is one: [GQE-425](https://ctds-planx.atlassian.net/browse/GQE-425)
[GQE-425]: https://ctds-planx.atlassian.net/browse/GQE-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change release notes PR label

- repo_list.txt
Link to JIRA ticket if there is one: [GQE-401](https://ctds-planx.atlassian.net/browse/GQE-401)
[GQE-401]: https://ctds-planx.atlassian.net/browse/GQE-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add gen3-user-data-library to gen3-release-utils
